apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUd
    server: https://30a61e37-a864-4140-8dd9.k8s.ondigitalocean.com
  name: do-fra1-k8s-1-14-5-do-0-fra1-1565441425291
contexts:
- context:
    cluster: do-fra1-k8s-1-14-5-do-0-fra1-1565441425291
    user: do-fra1-k8s-1-14-5-do-0-fra1-1565441425291-admin
  name: do-fra1-k8s-1-14-5-do-0-fra1-1565441425291
current-context: do-fra1-k8s-1-14-5-do-0-fra1-1565441425291
kind: Config
preferences: {}
users:
- name: do-fra1-k8s-1-14-5-do-0-fra1-1565441425291-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTi
    client-key-data: LS0tLS1CRUdJTiBSU0EgUF
